server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/api/reportes/**
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/api/vehiculos/**
        - id: reparacionesVehiculo-service
          uri: lb://reparacionesVehiculo-service
          predicates:
            - Path=/api/reparaciones/**